Allow to specify the spec file to use
rhysd/vim-crystal pull request #68
Opened 2019-03-10 20:17 UTC by bew

Fixes #66 

It'll check if there is a `b:crystal_spec_file`, then `g:crystal_spec_file`, then fallback to require all specs.

2019-03-26 09:45 UTC, rhysd commented
I'm sorry for the delay.

Let me review

2019-03-26 09:49 UTC, rhysd requested changes

2019-03-26 09:49 UTC, rhysd commented on autoload/crystal_lang.vim
> +    let spec_for_file = get(b:, 'crystal_spec_file', get(g:, 'crystal_spec_file', ''))
I prefer more descriptive variable name. How about `crystal_required_spec_path`? To clarify it represents files to run specific spec, I feel adding `required` would be obvious. And the value is actually (globbed) path. So I prefer 'path' to 'file'.

2019-04-04 16:27 UTC, bew commented
I updated with a more descriptive name as you suggested!

2019-09-27 08:23 UTC, rhysd approved these changes

2019-09-27 08:23 UTC, merged

2019-09-27 08:25 UTC, rhysd commented
I'm sorry that I overlooked your updates. Looks good and merged.

2019-09-27 10:28 UTC, bew commented
No problem, I used my fork in the meantime ;)

Thanks!