Replace '\@<=' and '\@<!' with faster counterparts when possible
rhysd/vim-crystal pull request #92
Opened 2020-04-05 19:20 UTC by jlcrochet

According to `:h \@<=`, `\zs` should be preferred to `\@<=` whenever possible due to better performance, so I decided to make a pass and try to replace the latter with the former wherever possible. Additionally, I tried to replace `\@<!` with `\@1<!` wherever I could without breaking any patterns.

2020-04-06 03:46 UTC, rhysd commented
yeah, I know the performance issue in `\@<!`. However, `\zs` does not work in syntax highlight matching (though I don't know why).

I tried this branch and some highlights seem not working.

```crystal
[1, 2, 3].each do |x|
  puts x
end
```

I found `x` in `|x|` is not highlighted. Some other highlights may not be working. Would you check the changes work fine?

2020-04-06 05:38 UTC, jlcrochet commented
You're right, I didn't realize that. I don't like the idea of using lookbehinds, but it seems the only viable alternative is to break matches up and chain them together using `nextgroup`, which would require a lot of refactoring.

I've put the lookbehinds back in and have tried to add the one-byte restriction to a few of them.

2020-04-08 01:48 UTC, rhysd requested changes

2020-04-08 01:48 UTC, rhysd commented on syntax/crystal.vim
> +syn match crystalPredefinedConstant "\%(\%(\.\@1<!\.\)\@1<!\|::\)\_s*\zs\%(crystal_\%(VERSION\|RELEASE_DATE\|PLATFORM\|PATCHLEVEL\|REVISION\|DESCRIPTION\|COPYRIGHT\|ENGINE\)\)\>\%(\s*(\)\@!"
```suggestion
syn match crystalPredefinedConstant "\%(\%(\.\@1<!\.\)\@2<!\|::\)\_s*\zs\%(MatchingData\|ARGF\|ARGV\|ENV\)\>\%(\s*(\)\@!"
syn match crystalPredefinedConstant "\%(\%(\.\@1<!\.\)\@2<!\|::\)\_s*\zs\%(DATA\|FALSE\|NIL\)\>\%(\s*(\)\@!"
syn match crystalPredefinedConstant "\%(\%(\.\@1<!\.\)\@2<!\|::\)\_s*\zs\%(STDERR\|STDIN\|STDOUT\|TOPLEVEL_BINDING\|TRUE\)\>\%(\s*(\)\@!"
syn match crystalPredefinedConstant "\%(\%(\.\@1<!\.\)\@2<!\|::\)\_s*\zs\%(crystal_\%(VERSION\|RELEASE_DATE\|PLATFORM\|PATCHLEVEL\|REVISION\|DESCRIPTION\|COPYRIGHT\|ENGINE\)\)\>\%(\s*(\)\@!"
```

Shouldn't we use `\@2` here? It checks dot which is not following another dot. So I thought 2 characters need to be looked up.

2020-04-08 14:35 UTC, rhysd approved these changes
Thank you for the updates.

2020-04-08 14:35 UTC, merged